config/routes.rb
Rails.application.routes.draw do

  get 'tagged' => 'artworks#index', :as => 'tagged'
  get 'series' => 'artworks#index', :as => 'series'
  get 'sold' => 'artworks#sold', :as => 'sold'
  get 'unsold' => 'artworks#unsold', :as => 'unsold'
  get 'landscape' => 'artworks#landscape', :as => 'landscape'
  get 'stilllife' => 'artworks#stilllife', :as => 'stilllife'
  get 'figure' => 'artworks#figure', :as => 'figure'
  get 'interior' => 'artworks#interior', :as => 'interior'
  get 'oil' => 'artworks#oil', :as => 'oil'
  get 'watercolor' => 'artworks#watercolor', :as => 'watercolor'
  get 'inkwash' => 'artworks#inkwash', :as => 'inkwash'
  get 'charcoal' => 'artworks#charcoal', :as => 'charcoal'
  get 'graphite' => 'artworks#graphite', :as => 'graphite'
  get 'paintings' => 'artworks#paintings', :as => 'paintings'
  get 'drawings' => 'artworks#drawings', :as => 'drawings'
  get 'sculpture' => 'artworks#sculpture', :as => 'sculpture'

  devise_for :users, :skip => :registrations

  root "artworks#index"
  get "about" => "pages#about"
  get "admin" => "artworks#admin"

  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts, only: [:new, :create]

  resources :artworks, path: ''

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"
 

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  # default_scope { order('rating DESC') } #trying to order by rating
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  #validates_presence_of :name, :category #to ensure that page titles have both of these

  acts_as_taggable
  acts_as_taggable_on :tags, :series

  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :history]
  def slug_candidates
    [
      :title,
      [:title, :date],
      [:title, :date, :genre],
      [:title, :date, :genre, :category],
      [:title, :date, :genre, :category, :medium]
    ]
  end

  def previous
    Artwork.where(["id < ?", id]).last
  end

  def next
    Artwork.where(["id > ?", id]).first
  end

end

app/models/contact.rb
class Contact < MailForm::Base
  #include MailForm::Delivery

  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Message from visitor at peter-bentley.com",
      :to => "peter@peter-bentley.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :create, :update, :destroy, :admin]

  # GET /artworks
  # GET /artworks.json
  def index
    if params[:tag] 
      @artworks = Artwork.tagged_with(params[:tag])
    elsif params[:series]
      @artworks = Artwork.tagged_with(params[:series])
    else
      @artworks = Artwork.all
    end
  end

  def tagged
      @artworks = Artwork.tagged_with(params[:tag])
  end

  def series
      @artworks = Artwork.tagged_with(params[:series]) 
  end

  def admin
    @artworks = Artwork.all
  end

  def sold
    @artworks = Artwork.where(availability: 'Private collection')
    render :index
  end

  def unsold
    @artworks = Artwork.where(availability: 'Available for purchase')
    render :index
  end

  def landscape
    @artworks = Artwork.where(genre: 'Landscape')
    render :index
  end

  def stilllife
    @artworks = Artwork.where(genre: 'Still life')
    render :index
  end

  def figure
    @artworks = Artwork.where(genre: 'Figure')
    render :index
  end

  def interior
    @artworks = Artwork.where(genre: 'Interior')
    render :index
  end

  def oil
    @artworks = Artwork.where(medium: ['Oil on paper', 'Oil on canvas', 'Oil on canvas mounted on panel', 'Oil pastel'])
    render :index
  end

  def watercolor
    @artworks = Artwork.where(medium: 'Watercolor')
    render :index
  end

  def inkwash
    @artworks = Artwork.where(medium: 'Ink wash')
    render :index
  end

  def charcoal
    @artworks = Artwork.where(medium: 'Charcoal')
    render :index
  end

  def graphite
    @artworks = Artwork.where(medium: 'Graphite')
    render :index
  end

  def paintings
    @artworks = Artwork.where(category: 'Painting')
    render :index
  end

  def drawings
    @artworks = Artwork.where(category: 'Drawing')
    render :index
  end

  def sculpture
    @artworks = Artwork.where(category: 'Sculpture')
    render :index
  end

  # GET /artworks/1
  # GET /artworks/1.json
  def show
    @artwork = Artwork.friendly.find(params[:id])
    # if request.path != artwork_path(@artwork)
    #   redirect_to @artwork, status: :moved_permanently
    # end
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks
  # POST /artworks.json
  def create
    @artwork = Artwork.new( artwork_params )

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to @artwork, notice: 'Artwork was successfully created.' }
        format.json { render :show, status: :created, location: @artwork }
      else
        format.html { render :new }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artworks/1
  # PATCH/PUT /artworks/1.json
  def update
    respond_to do |format|
      if @artwork.update(artwork_params)
        format.html { redirect_to @artwork, notice: 'Artwork was successfully updated.' }
        format.json { render :show, status: :ok, location: @artwork }
      else
        format.html { render :edit }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1
  # DELETE /artworks/1.json
  def destroy
    @artwork.destroy
    respond_to do |format|
      format.html { redirect_to @artwork, notice: 'Artwork was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artwork
      @artwork = Artwork.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artwork_params
      params.require(:artwork).permit(:title, :category, :image, :genre, :medium, :slug, :availability, :date, :height, :width, :rating, :tag_list, :tag, :region, :series_list, :series)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
 
  def not_found
    render :status => 404
  end
 
  def unacceptable
    render :status => 422
  end
 
  def internal_error
    render :status => 500
  end
 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about 
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	# def index
 #    if params[:approved] == "false"
 #      @users = User.find_all_by_approved(false)
 #    else
 #      @users = User.all
 #    end
 #  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

def title(page_title)
  content_for(:title) { page_title }
end

app/helpers/artworks_helper.rb
module ArtworksHelper
	include ActsAsTaggableOn::TagsHelper #do I need to include this?
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/artworks/_form.html.erb
<%= simple_form_for @artwork, :html => {:multipart => true } do |f| %>
  <% if @artwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% @artwork.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-4">
    <%= f.input :image %>
      </div>
    <div class="col-md-8">
      <%= f.input :title %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= f.input :genre, :collection => ['Landscape', 'Still life', 'Figure', 'Interior'], :include_blank => false, :as => :radio_buttons %>
    </div>

    <div class="col-md-2">
      <%= f.input :category, :collection => ['Painting', 'Drawing', 'Sculpture', 'Print', 'Mixed media'], :include_blank => false, :as => :radio_buttons %> 
    </div>

    <div class="col-md-3">
      <%= f.input :medium, :collection => ['Oil on paper', 'Oil on canvas', 'Oil on canvas mounted on panel', 'Watercolor', 'Ink wash', 'Charcoal', 'Graphite', 'Oil pastel'] %>
      <%= f.input :date, :include_blank => true, as: :string, start_year: Time.now.year - 100, end_year: Time.now.year, order: [ :year, :month, :day,], hint: 'Order: Year, month, date' %>
    </div>
    <div class="col-md-2">
      <%= f.input :height %>
      <%= f.input :width %>
    </div>
    <div class="col-md-3">
      <%= f.input :availability, :collection => ['Available for purchase','Private collection','Not for sale'],  :as => :radio_buttons %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="form-inline">
        <%= f.input :rating,
        collection: 1..10,
        as: :radio_buttons,
        hint: '1 is least, 10 is best',
        item_wrapper_class: 'inline' %>
      </div>
    </div>
    
    <div class="col-md-3">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>

  </div>

  <div class="row">

    <div class="col-md-4">
      <%= f.input :tag_list, hint: 'Tags (separated by commas)' %>
    </div>

    <div class="col-md-4">
      <%= f.input :series_list, hint: 'Series (separated by commas)' %>
    </div>

    <div class="col-md-4">
      <%= f.input :region, hint: 'e.g. Northwest, Florence' %>
    </div>

    <div class="col-md-4">
      <%= f.input :notes %>
    </div>  
    
  </div>

<% end %>

app/views/artworks/admin.html.erb
<% if current_user.admin? %> 
  <h2>All <%= @artworks.count %> Artworks </h2>  
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Image</th>
          <th>Title</th>
          <th>Series</th>
          <th>Genre</th>
          <th>Category</th>
          <th>Medium</th>
          <th>Date</th>
          <th>Dimensions</th>
          <th>Availability</th>
          <th>Rating</th>
          <th>Tags</th>
          <th>Edit</th>
        </tr>
      </thead>

      <tbody>
        <% @artworks.each do |artwork| %>
          <tr>
            <td><%= link_to image_tag(artwork.image.url(:thumb)), artwork %></td>
            <td><%= artwork.title %></td>
            <td><%= artwork.series_list %></td>
            <td><%= artwork.genre %></td>
            <td><%= artwork.category %></td>
            <td><%= artwork.medium %></td>
            <td><%= artwork.date %></td>
            <td><% if artwork.height.present? %>
              <%= artwork.height %> x <%= artwork.width %>
            <% end %></td>
            <td><%= artwork.availability %></td>
            <td><%= artwork.rating %></td>
            <td><%= artwork.tag_list %></td>
            <td><%= link_to 'Edit', edit_artwork_path(artwork) %></td>
            <td></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/artworks/edit.html.erb
<h1>Editing artwork</h1>

<%= render 'form' %>

<%= link_to 'See detail page', @artwork %> |
<%= link_to "Delete", @artwork, :method => :delete, data: {confirm: "Are you sure you want to delete this?"} %> |
<%= link_to 'Artworks Table', artworks_path %>

app/views/artworks/index.html.erb
<h1 class="center">Original Drawings &amp; Paintings from Life</h1>
<div class="row">
	<div class="col-sm-2">
		<ul class="list-unstyled">
			<li><%= link_to "All Works", root_path %></li>
		</ul>

		<p class="field-label">Availability</p>
		<ul class="list-unstyled">
			<li><%= link_to "Sold", sold_path %></li>
			<li><%= link_to "Unsold", unsold_path %></li>
		</ul>
		<p class="field-label">Genre</p>
		<ul class="list-unstyled">
			<li><%= link_to "Landscape", landscape_path %></li>
			<li><%= link_to "Still life", stilllife_path %></li>
			<li><%= link_to "Figure", figure_path %></li>
			<li><%= link_to "Interior", interior_path %></li>
		</ul>

		<p class="field-label">Medium</p>
		<ul class="list-unstyled">
			<li><%= link_to "Oil", oil_path %></li>
			<li><%= link_to "Watercolor", watercolor_path %></li>
			<li><%= link_to "Charcoal", charcoal_path %></li>
			<li><%= link_to "Ink Wash", inkwash_path %></li>
			<li><%= link_to "Graphite", graphite_path %></li>
		</ul>

		<p class="field-label">Series</p>
		<ul class="list-unstyled">
			
		</ul>

		<p class="field-label">Category</p>
			
		<ul class="list-unstyled">
			<li><%= link_to "Paintings", paintings_path %></li>
			<li><%= link_to "Drawings", drawings_path %></li>
			<li><%= link_to "Sculpture", sculpture_path %></li>			
		</ul>

		<p class="field-label">Tags</p>
		<ul class="list-unstyled">
			
		</ul>
	</div>

	<div class="col-sm-10">
		<div id="artworks" class="transitions-enabled">
			  <% @artworks.each do |artwork| %>
			    <div class="box">
		        <%= link_to image_tag(artwork.image.url(:medium)), artwork %>
			    </div>
			  <% end %>
		</div>
	</div>

</div> <!-- end of row div -->

app/views/artworks/new.html.erb
<h1>New artwork</h1>

<%= render 'form' %>

<%= link_to 'Back', artworks_path %>

app/views/artworks/show.html.erb
<%- title "#{@artwork.title} — a #{@artwork.category.downcase} by Peter Bentley"%>

<% if user_signed_in? %>
	<div class="row">
		<div class="col-md-12">
			<%= link_to 'Edit', edit_artwork_path(@artwork) %> |
			<%= link_to 'Artworks Table', admin_path %>
		</div>
	</div>
<% end %>



<div class="row">
	<div class="col-md-8">
  	<%= image_tag(@artwork.image.url, :class => 'img-responsive') %>
  </div>

	<div class="col-md-4">
		<div class="row">
		  <div class="col-xs-12 col-sm-12">
		  	<p class="field-label">Title</p>
		  	<h1><%= @artwork.title %></h1>
		  </div>

		  <div class="col-xs-6 col-sm-12">
		  	<p class="field-label">Medium</p>
		  	<h3><%= @artwork.medium %></h3>
		  </div>

		  <% unless @artwork.date.blank? %>	
				<div class="col-xs-6 col-sm-6">
					<p class="field-label">Date</p>
					<h3><%= @artwork.date.strftime("%b %d %Y") %></h3>
				</div>
			<% end %>

			<% unless @artwork.height.blank? | @artwork.width.blank?%>	
				<div class="col-xs-6 col-sm-6">
					<p class="field-label">Size</p>
					<h3><%= @artwork.height %> x <%= @artwork.width %> in.</h3>
				</div>
			<% end %>

			<% unless @artwork.series.blank? %>
			  <div class="col-xs-6 col-sm-12">
			    <p class="field-label">Series</p>
			    <% @artwork.series.each do |series| %>
			      <span class="tags">
			        <%= link_to series.name, series_url(:series => series.name) %>
			      </span><br><br>
			    <% end %>
			  </div>
			<% end %>

			<% unless @artwork.availability.blank? %>	
				<div class="col-xs-12 col-sm-12">
					<% if @artwork.availability == 'Available for purchase' %>
						<p class="field-label">Availability</p>
						<h3><%= @artwork.availability %></h3>
						<%= link_to "Add to Inquiry List", root_path, class: "btn btn-primary" %>
					<% else %>
						<p class="field-label">Availability</p>
						<h3><%= @artwork.availability %></h3>				
					<% end %>
				</div>
			<% end %>

			<div class="col-xs-6 col-sm-6">
				<p class="field-label">Genre</p>
				<h3><%= @artwork.genre %></h3>
			</div>
			<div class="col-xs-6 col-sm-6">
				<p class="field-label">Category</p>
				<h3><%= @artwork.category %></h3>
			</div>

			<% unless @artwork.region.blank? %>	
				<div class="col-xs-6 col-sm-6">
					<p class="field-label">Region</p>
					<h3><%= @artwork.region %></h3>
				</div>
			<% end %>

			<% unless @artwork.tags.blank? %>
			  <div class="col-xs-6 col-sm-12">
			    <p class="field-label">Tags</p>
			    <% @artwork.tags.each do |tag| %>
			      <span class="tags">
			        <%= link_to tag.name, tagged_url(:tag => tag.name) %>
			      </span>
			    <% end %>
			  </div>
			<% end %>
		</div>
	</div>
</div> <!-- end of 'row' div -->

app/views/contacts/create.html.erb
<!-- <div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div> -->

Here is some temporary text.

app/views/contacts/new.html.erb
<div align="center">
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer id="footer" class="footer">
  <div class="container">
    <ul class="list-inline center ">
    	<li><p class="text-muted">All artworks &copy; Peter Bentley.</p></li>
	     <% if user_signed_in? %>
	        <li> <%= link_to 'Add Artwork', new_artwork_path %> </li>
	        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
	      <% end %>
	      <li><%= link_to "About", about_path %></li>
	    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div id="topline" class="row row-centered" >
    <div class="col-sm-4 col-centered">
      <% if @artwork.present?  %>
        <% if @artwork.previous.present? %>
          <%= link_to "&larr; Previous".html_safe, @artwork.previous %>
        <% end %>
      <% end %>
    </div>     
    <div class="col-sm-4 col-centered">     
      <%= link_to image_tag("PeterBentley_mark.png"), root_path %>
    </div>
    <div class="col-sm-4 col-centered">
      <% if @artwork.present?  %>
        <% if @artwork.next.present?  %>
          <%= link_to "Next &rarr;".html_safe, @artwork.next %>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>


      <!-- If I want a collapsed nav:
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>    
      </div>

      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-left">
            <li></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li></li>
        </ul>
      </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? content_for(:title) : "Peter Bentley — Drawings and Paintings from Life" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="sticky-footer.css" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrap">
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |name, msg| %>
	     <%= content_tag(:div, msg, class: "alert alert-info") %>
			<% end %>
			<%= yield %>
		</div>
	</div>
		<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/reserveHeader.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="row">
    <div class="col-md-12">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>    
      </div>
      <%= link_to image_tag("PeterBentley_mark.png"), root_path, :class => "navbar-brand" %>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "&larr; Previous".html_safe,  @artwork.previous if @artwork.previous.present? %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Next &rarr;".html_safe, @artwork.next if @artwork.next.present? %></li>
        </ul>
      </div>

    </div>
  </div>
</nav>

<!-- <nav class="navbar navbar-default" role="navigation">
  <div class="container"> -->
    <!-- Brand and toggle get grouped for better mobile display -->
      
    <!-- <div class="navbar-header">
      <div class="row">
        <div class="col-md-6 text-center">
            <%= link_to "&larr; Previous".html_safe,  @artwork.previous if @artwork.previous.present? %>  
              <%= link_to image_tag("PeterBentley_mark.png"), root_path %>          
          <%= link_to "Next &rarr;".html_safe, @artwork.next if @artwork.next.present? %>
        </div>
      </div>
    </div> -->
    

      <!-- <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div> -->

      <!-- Collect the nav links, forms, and other content for toggling -->
<!--       <div class="collapse navbar-collapse navbar-ex1-collapse">
 -->    
        
      <!-- </div> --> <!-- /.navbar-collapse --> 
    

    <!-- <div class="row row-centered">
        <div class="col-md-2 col-centered">
            <%= link_to "&larr; Previous".html_safe,  @artwork.previous if @artwork.previous.present? %>  
        </div>
        <div class="col-md-3 col-centered">
              <%= link_to image_tag("PeterBentley_mark.png"), root_path %>          
        </div>
        <div class="col-md-2 col-centered">
          <%= link_to "Next &rarr;".html_safe, @artwork.next if @artwork.next.present? %>
        </div>
        
      </div>  -->

  <!-- </div> --> <!-- end of container div -->
<!-- </nav> -->

app/views/pages/about.html.erb
<%- title "About — Peter Bentley"%>
<div class="row">
	<div class="col-md-9 col-md-offset-2">
		<h1>I'm a Seattle artist fascinated by the way that light describes form. I work from direct observation to represent the vitality of everyday life in oil, charcoal, watercolor and ink.</h1>
		<h2>Resume</h2>
		<p>For exhibition history, education and awards, please download my resume:</p>
		<a href="" class="btn btn-default">Printable Version (.pdf)</a>
	</div>
</div>
		
<!-- 	What say I scratch this whole idea of putting my resume on the page (besides the link)	
<div class="row">
	<div class="col-md-12">
		<h3>Exhibitions</h3>
	</div>
	<div class="col-md-2">
		2014
	</div>
	<div class="col-md-8">
		<p>Exhibition example 1</p>
		<p>Exhibition example 2</p>
		<p>Exhibition example 3</p>
	</div>
</div> -->


<div class="row">
	<div class="col-md-7 col-md-offset-2">
		<h2>Commissions</h2>
		Text
		<h2>Sales</h2>
			From time to time I've shown in galleries across the U.S. though I am currently not represented by one. If you're a gallery interested in representing my work, on an individual interested in purchasing a work, please <a href="">contact me.</a>
		<h2>Shipping</h2>
		
		<a href="" class="btn btn-primary">Contact Me</a>
	</div>
</div>
		